#ifndef NATIVE_WRAPPER_H
#define NATIVE_WRAPPER_H

#include "ats_define.hpp"
typedef void (WINAPI* DETAILMODULE_ATSLOAD)(void);
typedef void (WINAPI* DETAILMODULE_ATSDISPOSE)(void);
typedef int (WINAPI* DETAILMODULE_ATSGETPLUGINVERSION)(void);
typedef void (WINAPI* DETAILMODULE_ATSSETVEHICLESPEC)(ATS_VEHICLESPEC);
typedef void (WINAPI* DETAILMODULE_ATSINITIALIZE)(int);
typedef ATS_HANDLES(WINAPI* DETAILMODULE_ATSELAPSE)(ATS_VEHICLESTATE, int*, int*);
typedef void (WINAPI* DETAILMODULE_ATSSETPOWER)(int);
typedef void (WINAPI* DETAILMODULE_ATSSETBRAKE)(int);
typedef void (WINAPI* DETAILMODULE_ATSSETREVERSER)(int);
typedef void (WINAPI* DETAILMODULE_ATSKEYDOWN)(int);
typedef void (WINAPI* DETAILMODULE_ATSKEYUP)(int);
typedef void (WINAPI* DETAILMODULE_ATSHORNBLOW)(int);
typedef void (WINAPI* DETAILMODULE_ATSDOOROPEN)(void);
typedef void (WINAPI* DETAILMODULE_ATSDOORCLOSE)(void);
typedef void (WINAPI* DETAILMODULE_ATSSETSIGNAL)(int);
typedef void (WINAPI* DETAILMODULE_ATSSETBEACONDATA)(ATS_BEACONDATA);

struct ST_DETAILMODULE_ATS_DELEGATE_FUNC
{
    HMODULE hm_dll;
    DETAILMODULE_ATSLOAD atsLoad;
    DETAILMODULE_ATSDISPOSE atsDispose;
    DETAILMODULE_ATSGETPLUGINVERSION atsGetPluginVersion;
    DETAILMODULE_ATSSETVEHICLESPEC atsSetVehicleSpec;
    DETAILMODULE_ATSINITIALIZE atsInitialize;
    DETAILMODULE_ATSELAPSE atsElapse;
    DETAILMODULE_ATSSETPOWER atsSetPower;
    DETAILMODULE_ATSSETBRAKE atsSetBrake;
    DETAILMODULE_ATSSETREVERSER atsSetReverser;
    DETAILMODULE_ATSKEYDOWN atsKeyDown;
    DETAILMODULE_ATSKEYUP atsKeyUp;
    DETAILMODULE_ATSHORNBLOW atsHornBlow;
    DETAILMODULE_ATSDOOROPEN atsDoorOpen;
    DETAILMODULE_ATSDOORCLOSE atsDoorClose;
    DETAILMODULE_ATSSETSIGNAL atsSetSignal;
    DETAILMODULE_ATSSETBEACONDATA atsSetBeaconData;
    ATS_HANDLES last_handle;
};

#endif // NATIVE_WRAPPER_H
